=== George-Boole/metadata-repo/Tier Content/Tier 2A/IRM/Examples/ISM/test_ism.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="test:ism"
   xmlns:ism="urn:us:gov:ic:ism" xmlns:arh="urn:us:gov:ic:arh" xmlns:ntk="urn:us:gov:ic:ntk" xmlns:test="test:ism">
   <xs:import namespace="urn:us:gov:ic:ism"
              schemaLocation="../../Schema/ISM/IC-ISM.xsd"/>
   <xs:import namespace="urn:us:gov:ic:arh"
              schemaLocation="../../Schema/ISM/IC-ARH.xsd"/>
   <xs:import namespace="urn:us:gov:ic:ntk"
              schemaLocation="../../Schema/ISM/IC-NTK.xsd"/>
   <xs:element name="root">
      <xs:complexType>
         <xs:sequence minOccurs="1" maxOccurs="unbounded">
            <xs:choice minOccurs="1" maxOccurs="1">
               <xs:element ref="test:singleElement" minOccurs="1" maxOccurs="1"/>
               <xs:element ref="test:parentElement" minOccurs="1" maxOccurs="unbounded"/>
               <xs:element ref="test:singleCUIONLYElement" minOccurs="1" maxOccurs="1"/>
               <xs:element ref="ism:NoticeList" minOccurs="1" maxOccurs="1"/>
               <xs:element ref="arh:Security" minOccurs="1" maxOccurs="1"/>
               <xs:element ref="arh:ExternalSecurity" minOccurs="1" maxOccurs="1"/>
            </xs:choice>
         </xs:sequence>
         <xs:attribute ref="ism:DESVersion"/>
         <xs:attribute ref="arh:DESVersion"/>
         <xs:attribute ref="ism:ISMCATCESVersion"/>
         <xs:attributeGroup ref="ism:ResourceNodeAttributeOptionGroup"/>
         <!--<xs:attributeGroup ref="ntk:NTKRootNodeOptionAttributeGroup"/>-->
      </xs:complexType>
   </xs:element>
   <xs:element name="singleElement">
      <xs:complexType mixed="true">
         <xs:attributeGroup ref="ism:NoticeAttributesGroup"/>
         <xs:attributeGroup ref="ism:POCAttributeGroup"/>
         <xs:attribute ref="ism:excludeFromRollup"/>
      </xs:complexType>
   </xs:element>
   <xs:element name="parentElement">
      <xs:complexType mixed="true">
         <xs:sequence minOccurs="1" maxOccurs="unbounded">
            <xs:choice minOccurs="1" maxOccurs="1">
               <xs:element ref="test:childElement" minOccurs="1" maxOccurs="1"/>
               <xs:element ref="ism:NoticeList" minOccurs="0" maxOccurs="1"/>
            </xs:choice>
         </xs:sequence>
         <xs:attributeGroup ref="ism:ResourceNodeAttributeOptionGroup"/>
         <xs:attributeGroup ref="ism:POCAttributeGroup"/>
      </xs:complexType>
   </xs:element>
   <xs:element name="childElement">
      <xs:complexType mixed="true">
         <xs:sequence minOccurs="0" maxOccurs="unbounded">
            <xs:choice minOccurs="1" maxOccurs="1">
               <xs:element ref="test:grandchildElement" minOccurs="1" maxOccurs="1"/>
               <xs:element ref="ism:NoticeList" minOccurs="0" maxOccurs="1"/>
            </xs:choice>
         </xs:sequence>
         <xs:attributeGroup ref="ism:NoticeAttributesGroup"/>
         <xs:attributeGroup ref="ism:POCAttributeGroup"/>
         <xs:attribute ref="ism:excludeFromRollup"/>
      </xs:complexType>
   </xs:element>
   <xs:element name="grandchildElement">
      <xs:complexType mixed="true">
         <xs:attributeGroup ref="ism:SecurityAttributesOptionGroup"/>
         <xs:attributeGroup ref="ism:POCAttributeGroup"/>
         <xs:attribute ref="ism:excludeFromRollup"/>
      </xs:complexType>
   </xs:element>
   <xs:element name="singleCUIONLYElement">
      <xs:complexType mixed="true">
         <xs:attributeGroup ref="ism:CUIONLYattributesGroup"/>
         <xs:attribute ref="ism:excludeFromRollup"/>
      </xs:complexType>
   </xs:element>
</xs:schema>

=== George-Boole/metadata-repo/Tier Content/Tier 2A/IRM-Public-Convenience-2022-DEC-Public/Examples/ISM/NATO-classified-2.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="../../Schematron/ISM/ISM_XML.sch" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<!-- Notices - Distribution Notice: 
           This document has been approved for Public Release and is available for use without restriction.
       -->
<!-- All classification marks in this example are   -->
<!-- for illustrative purposes only, there are no   -->
<!-- actual classified data contained in this example -->
<test:root xmlns:test="test:ism"
           xmlns:ism="urn:us:gov:ic:ism"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           ism:compliesWith="USGov"
           ism:DESVersion="202111.202211"
           ism:ISMCATCESVersion="202211"
           ism:resourceElement="true"
           ism:createDate="2009-06-01"
           ism:classification="S"
           ism:ownerProducer="USA"
           ism:FGIsourceOpen="GBR NATO"
           ism:disseminationControls="REL"
           ism:releasableTo="USA GBR NATO"
           ism:derivativelyClassifiedBy="John Smith"
           ism:derivedFrom="something"
           ism:declassException="NATO"
           xsi:schemaLocation="test:ism test_ism.xsd"
           ism:highWaterNATO="NATO-C">
  <arh:Security xmlns="test:ism"
                xmlns:arh="urn:us:gov:ic:arh"
                ism:classification="U"
                ism:ownerProducer="USA"
                ism:resourceElement="true"
                ism:compliesWith="OtherAuthority"
                ism:createDate="2019-12-19" />
  <test:parentElement ism:classification="C"
                      ism:ownerProducer="USA NATO"
                      ism:highWaterNATO="NATO-U"
                      ism:disseminationControls="REL"
                      ism:releasableTo="USA GBR NATO">Executive Summary: From 1754 to 1763 Europe and the Americas were caught up in a
                      conflict between England, under King George II, and France, under King Louis XV. In Europe this period was known as
                      the Seven Years' War; in North America it came to be called the French and Indian War. It was a conflict over trade
                      and land. 
  <test:childElement ism:classification="U"
                     ism:ownerProducer="NATO"
                     ism:disseminationControls="REL"
                     ism:releasableTo="USA GBR NATO">
    <test:grandchildElement ism:classification="U"
                            ism:ownerProducer="NATO"
                            ism:disseminationControls="REL"
                            ism:releasableTo="USA GBR NATO">Paragraph: The English sent Crown forces from England to fortify the colonies
                            and fight the French and Indian invaders, but it was also necessary to recruit soldiers from the colonial
                            population. The English army found that fighting an enemy in the near-wilderness of North America was too much
                            for their massed regiments. The dense forests and mountainous terrain required fighting men who knew the habits
                            of the enemy and could serve effectively as scouts and skirmishers .</test:grandchildElement>
    <test:grandchildElement ism:classification="U"
                            ism:ownerProducer="NATO"
                            ism:disseminationControls="REL"
                            ism:releasableTo="USA GBR NATO">Paragraph: Men from local communities and nearby states were recruited to join
                            ranger companies in the Hudson Valley campaign. The New Hampshireman Robert Rogers formed the most notable of
                            these ranger companies.</test:grandchildElement>
  </test:childElement>
  <test:childElement ism:classification="C"
                     ism:ownerProducer="NATO"
                     ism:disseminationControls="REL"
                     ism:releasableTo="USA GBR NATO"
                     ism:nonUSControls="NATO-BALK">Paragraph: Rogers grew up in southern New Hampshire, in an area which had known years of
                     murderous Indian raids. He had the knowledge and the spirit to make a good ranger commander, and both he and his
                     brother James joined the war in the King's service as rangers. Soon his own company, Rogers' Rangers, was in service
                     in the upper Hudson River area where they became known for their successful but unorthodox
                     tactics.</test:childElement></test:parentElement>
  <test:parentElement ism:classification="S"
                      ism:ownerProducer="GBR"
                      ism:disseminationControls="REL"
                      ism:releasableTo="USA GBR NATO">Paragraph: The Rangers wore distinctive green outfits and practiced tactics called
                      "Rogers' Rules of Ranging," which the British considered unconventional. Rogers hired men solely on merit and shocked
                      regular commanders with his use of Indians and freed slaves.</test:parentElement>
  <test:parentElement ism:classification="S"
                      ism:ownerProducer="USA"
                      ism:FGIsourceOpen="NATO"
                      ism:highWaterNATO="NATO-C"
                      ism:disseminationControls="REL"
                      ism:releasableTo="USA GBR NATO">All Rangers are to be subject to the rules and articles of war; to appear at roll-
                      call every evening, on their own parade, equipped, each with a Firelock, sixty rounds of powder and ball, and a
                      hatchet, at which time an officer from each company is to inspect the same, to see they are in order, so as to be
                      ready on any emergency to march at a minute's warning; and before they are dismissed, the necessary guards are to be
                      draughted, and scouts for the next day appointed.</test:parentElement>
</test:root>
